# scripts/always_on.py
# shared helper: extract skills' always-on blocks & manage the generated instruction-file region

from __future__ import annotations

import os
import re
from pathlib import Path


# per-skill source markers in SKILL.md
START_RE = re.compile(r"<!--\s*always-on:start[^>]*-->")
END_RE = re.compile(r"<!--\s*always-on:end\s*-->")
TITLE_RE = re.compile(r'title\s*=\s*"(?P<title>[^"]+)"')
# single pass over both marker kinds, in document order, for the ordered parser
MARKER_RE = re.compile(r"<!--\s*always-on:(?P<kind>start|end)\b(?P<attrs>[^>]*?)-->")

# managed region markers in the generated instruction file
REGION_BEGIN = "<!-- BEGIN ggfincke-skills:always-on -->"
REGION_END = "<!-- END ggfincke-skills:always-on -->"
REGION_RE = re.compile(re.escape(REGION_BEGIN) + r".*?" + re.escape(REGION_END), re.DOTALL)
# same span plus the blank lines around it, so removing it leaves no ragged seam
REGION_REMOVE_RE = re.compile(
    r"\n*" + re.escape(REGION_BEGIN) + r".*?" + re.escape(REGION_END) + r"\n*", re.DOTALL
)

# global agents that receive a generated instruction file
# name -> (home env var, default home dir, instruction filename)
AGENT_INSTRUCTION = {
    "codex": ("CODEX_HOME", ".codex", "AGENTS.md"),
    "agents": ("AGENTS_HOME", ".agents", "AGENTS.md"),
    "claude": ("CLAUDE_HOME", ".claude", "CLAUDE.md"),
}


def agent_home(agent: str) -> Path:
    # an empty env var counts as unset: Path("") is PosixPath("."), which would
    # silently aim the instruction file at whatever directory sync runs from
    env_var, default, _ = AGENT_INSTRUCTION[agent]
    return Path(os.environ.get(env_var) or Path.home() / default)


def instruction_file(agent: str) -> Path:
    return (agent_home(agent) / AGENT_INSTRUCTION[agent][2]).expanduser()


def parse_blocks(text: str) -> tuple[list[tuple[str, str]], list[str]]:
    # one ordered pass shared by extraction & validation so the two never diverge:
    # extraction emits only well-formed blocks; validation surfaces every malformation
    blocks: list[tuple[str, str]] = []
    errors: list[str] = []
    open_start: re.Match[str] | None = None

    for marker in MARKER_RE.finditer(text):
        if marker.group("kind") == "start":
            if open_start is not None:
                errors.append("nested always-on:start before the previous block closed")
                continue
            open_start = marker
            continue

        if open_start is None:
            errors.append("always-on:end marker without a matching always-on:start")
            continue

        start, open_start = open_start, None
        block_errors: list[str] = []

        title_match = TITLE_RE.search(start.group("attrs"))
        if not title_match:
            block_errors.append('always-on:start marker missing title="..." attribute')

        raw_body = text[start.end() : marker.start()]
        if not raw_body.startswith("\n"):
            block_errors.append("always-on:start marker must be alone on its line (newline before content)")

        content = raw_body.strip()
        title = title_match.group("title") if title_match else ""

        for delimiter, label in ((REGION_BEGIN, "begin"), (REGION_END, "end")):
            if delimiter in title or delimiter in content:
                block_errors.append(f"always-on block contains the generated-region {label} delimiter")
        if START_RE.search(content) or END_RE.search(content):
            block_errors.append("always-on block content contains a nested always-on marker")

        errors.extend(block_errors)
        if not block_errors:
            blocks.append((title, content))

    if open_start is not None:
        errors.append("unclosed always-on:start marker (no matching always-on:end)")

    return blocks, errors


def extract_blocks(text: str) -> list[tuple[str, str]]:
    # (title, content) for each well-formed always-on block
    return parse_blocks(text)[0]


def marker_issues(text: str) -> list[str]:
    # surface malformed markers so validation can fail fast
    return parse_blocks(text)[1]


def render_region(items: list[tuple[str, str, str]]) -> str:
    # items: (skill_name, title, content) -> a complete managed region
    parts = [
        REGION_BEGIN,
        "<!-- Generated by scripts/sync-skills.py from skill always-on blocks. "
        "Do not edit here; edit the source skill. -->",
        "",
        "# Always-on conventions",
        "",
        "These come from skills in ggfincke-skills. Apply them on every relevant "
        "change, without being asked or invoking the skill.",
    ]
    for skill_name, title, content in items:
        parts += [
            "",
            f"## {title}",
            "",
            f"_From the `{skill_name}` skill; full detail & enforcers there._",
            "",
            content,
        ]
    parts += ["", REGION_END]
    return "\n".join(parts)


def region_marker_error(existing: str) -> str | None:
    # the destination file is user-owned, so only two shapes are safe to touch:
    # no markers at all, or exactly one balanced pair. anything else (an orphan
    # BEGIN, a duplicated region, BEGIN after END) would make REGION_RE span the
    # user's own prose & the substitution would delete it
    begins = existing.count(REGION_BEGIN)
    ends = existing.count(REGION_END)
    if begins == 0 and ends == 0:
        return None
    if begins == 1 and ends == 1 and REGION_RE.search(existing):
        return None
    return (
        f"malformed always-on region markers ({begins} BEGIN, {ends} END); repair them by "
        "hand so exactly one BEGIN...END pair remains, then re-run sync"
    )


def apply_region(existing: str, region: str) -> str:
    # replace the managed region in place, else append it; preserve other content
    error = region_marker_error(existing)
    if error:
        raise SystemExit(error)
    if REGION_RE.search(existing):
        return REGION_RE.sub(lambda _match: region, existing).rstrip() + "\n"
    base = existing.rstrip()
    if base:
        return base + "\n\n" + region.rstrip() + "\n"
    return region.rstrip() + "\n"


def remove_region(existing: str) -> str:
    # strip the managed region when no always-on blocks remain repo-wide,
    # leaving the user's surrounding content intact
    error = region_marker_error(existing)
    if error:
        raise SystemExit(error)
    # newlines only on the leading side: a blanket .strip() would eat the indent
    # of a first line that is a 4-space Markdown code block, silently demoting it
    # to a paragraph. trailing side rstrips to stay symmetric w/ apply_region
    remainder = REGION_REMOVE_RE.sub("\n\n", existing).strip("\n").rstrip()
    return remainder + "\n" if remainder else ""
