# scripts/always_on.py
# shared helper: extract skills' always-on blocks & manage the generated region
# in each agent's global instruction file

from __future__ import annotations

import os
import re
from pathlib import Path


# per-skill source markers in SKILL.md
START_RE = re.compile(r"<!--\s*always-on:start[^>]*-->")
END_RE = re.compile(r"<!--\s*always-on:end\s*-->")
TITLE_RE = re.compile(r'title\s*=\s*"(?P<title>[^"]+)"')
BLOCK_RE = re.compile(
    r"<!--\s*always-on:start(?P<attrs>[^>]*?)-->\n(?P<body>.*?)\n?<!--\s*always-on:end\s*-->",
    re.DOTALL,
)

# managed region markers in the generated instruction file
REGION_BEGIN = "<!-- BEGIN ggfincke-skills:always-on -->"
REGION_END = "<!-- END ggfincke-skills:always-on -->"
REGION_RE = re.compile(re.escape(REGION_BEGIN) + r".*?" + re.escape(REGION_END), re.DOTALL)

# global agents that receive a generated instruction file
# name -> (home env var, default home dir, instruction filename)
AGENT_INSTRUCTION = {
    "codex": ("CODEX_HOME", ".codex", "AGENTS.md"),
    "agents": ("AGENTS_HOME", ".agents", "AGENTS.md"),
    "claude": ("CLAUDE_HOME", ".claude", "CLAUDE.md"),
}


def agent_home(agent: str) -> Path:
    env_var, default, _ = AGENT_INSTRUCTION[agent]
    return Path(os.environ.get(env_var, Path.home() / default))


def instruction_file(agent: str) -> Path:
    return (agent_home(agent) / AGENT_INSTRUCTION[agent][2]).expanduser()


def extract_blocks(text: str) -> list[tuple[str, str]]:
    # return (title, content) for each well-formed always-on block
    blocks: list[tuple[str, str]] = []
    for match in BLOCK_RE.finditer(text):
        title_match = TITLE_RE.search(match.group("attrs"))
        title = title_match.group("title") if title_match else "Untitled"
        blocks.append((title, match.group("body").strip()))
    return blocks


def marker_issues(text: str) -> list[str]:
    # surface malformed markers so validation can fail fast
    starts = list(START_RE.finditer(text))
    ends = END_RE.findall(text)
    issues: list[str] = []
    if len(starts) != len(ends):
        issues.append(
            f"unbalanced always-on markers: {len(starts)} start vs {len(ends)} end"
        )
    for marker in starts:
        if not TITLE_RE.search(marker.group(0)):
            issues.append('always-on:start marker missing title="..." attribute')
    return issues


def render_region(items: list[tuple[str, str, str]]) -> str:
    # items: (skill_name, title, content) -> a complete managed region
    parts = [
        REGION_BEGIN,
        "<!-- Generated by scripts/sync-skills.py from skill always-on blocks. "
        "Do not edit here; edit the source skill. -->",
        "",
        "# Always-on conventions",
        "",
        "These come from skills in ggfincke-skills. Apply them on every relevant "
        "change, without being asked or invoking the skill.",
    ]
    for skill_name, title, content in items:
        parts += [
            "",
            f"## {title}",
            "",
            f"_From the `{skill_name}` skill; full detail & enforcers there._",
            "",
            content,
        ]
    parts += ["", REGION_END]
    return "\n".join(parts)


def apply_region(existing: str, region: str) -> str:
    # replace the managed region in place, else append it; preserve other content
    if REGION_RE.search(existing):
        return REGION_RE.sub(lambda _match: region, existing).rstrip() + "\n"
    base = existing.rstrip()
    if base:
        return base + "\n\n" + region.rstrip() + "\n"
    return region.rstrip() + "\n"
