#!/usr/bin/env python3
# scripts/compile-skill-references.py
# package neutral review protocols and compile the separate react rule collections

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

from skill_inventory import _scan_markdown_links, parse_frontmatter_text

ROOT = Path(__file__).resolve().parents[1]
COLLECTIONS = {
	"performance": "React Performance Rules",
	"composition": "React Composition Patterns",
}
SHARED_REVIEW_CONSUMERS = (
	"architecture-review",
	"consolidation-audit",
	"simplification-review",
	"docs-freshness-audit",
	"test-coverage-audit",
	"test-pruning-audit",
	"mega-review",
	"mega-review-core",
	"security-remediation",
	"phased-implementation",
	"working-conventions",
)
SECTION_RE = re.compile(r"^## (\d+)\. (.+) \(([-a-z0-9]+)\)$", re.MULTILINE)


def anchor(title: str) -> str:
	return re.sub(r"[^\w -]", "", title.lower()).replace(" ", "-")


def rebase_sibling_links(line: str, collection: str) -> str:
	# reuse the validator's parser so inline code and escaped links stay untouched
	for link in reversed(_scan_markdown_links(line)):
		if link.destination is None or link.destination_start is None:
			continue
		destination = link.destination
		start = link.destination_start
		if destination.startswith("<"):
			destination = destination[1:-1]
			start += 1
		if destination.startswith("./"):
			line = line[:start] + f"../rules/{collection}/" + line[start + 2 :]
	return line


def read_sections(text: str) -> list[dict[str, str]]:
	matches = list(SECTION_RE.finditer(text))
	if not matches:
		raise ValueError("no rule sections found")
	sections = []
	for index, match in enumerate(matches):
		end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
		body = text[match.end() : end]
		impact = re.search(r"^\*\*Impact:\*\* (.+)$", body, re.MULTILINE)
		description = re.search(r"\*\*Description:\*\* (.+)", body, re.DOTALL)
		if impact is None or description is None:
			raise ValueError(f"section {match.group(1)} is missing impact or description")
		sections.append(
			{
				"number": match.group(1),
				"title": match.group(2),
				"prefix": match.group(3),
				"impact": impact.group(1),
				"description": " ".join(description.group(1).split()),
			}
		)
	return sections


def rule_body(text: str, title: str, collection: str) -> str:
	lines = text.splitlines()
	end = lines[1:].index("---") + 1
	body = "\n".join(lines[end + 1 :]).strip()
	heading, _, remainder = body.partition("\n")
	if not heading.startswith("## "):
		raise ValueError(f"rule is missing its leading heading: {title}")
	# keep fenced examples byte-for-byte while nesting ordinary subheadings
	result = []
	fence = None
	for line in remainder.strip().splitlines():
		marker = re.match(r"^\s*(`{3,}|~{3,})", line)
		if marker:
			value = marker.group(1)
			if fence is None:
				fence = value
			elif value[0] == fence[0] and len(value) >= len(fence):
				fence = None
		elif fence is None:
			line = rebase_sibling_links(line, collection)
			if line.startswith("##"):
				line = "##" + line
		result.append(line)
	return "\n".join(result)


def compile_collection(directory: Path, title: str) -> str:
	metadata_path = directory / "metadata.json"
	section_path = directory / "_sections.md"
	metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
	sections = read_sections(section_path.read_text(encoding="utf-8"))
	rules = []
	inputs = [metadata_path, section_path]
	for path in sorted(directory.glob("*.md")):
		if path.name.startswith("_"):
			continue
		text = path.read_text(encoding="utf-8")
		fields = parse_frontmatter_text(text)
		prefix = path.stem.split("-", 1)[0]
		if prefix not in {section["prefix"] for section in sections}:
			raise ValueError(f"unmapped rule section: {path.name}")
		rules.append((path, fields, rule_body(text, fields["title"], directory.name)))
		inputs.append(path)
	digest = hashlib.sha256()
	for path in sorted(inputs):
		digest.update(str(path.relative_to(directory)).encode() + b"\0" + path.read_bytes())
	lines = [
		f"<!-- Generated by scripts/compile-skill-references.py; edit rules/{directory.name}/. -->",
		f"# {title}",
		"",
		f"**Version {metadata['version']}**",
		f"{metadata['organization']} (source attribution; locally maintained adaptation)",
		"",
		f"`rules/{directory.name}/` is authoritative. Run `python3 scripts/compile-skill-references.py --check`",
		f"from the source repository to verify this snapshot. See [metadata](../rules/{directory.name}/metadata.json) for provenance.",
		"",
		f"Source set SHA-256: `{digest.hexdigest()}`",
		"",
		"## Abstract",
		"",
		metadata["abstract"],
		"",
		"Impact labels and numerical examples are heuristics, not target-application benchmarks.",
		"Check supported versions, preserve behavior, and verify performance on the actual workload.",
		"",
		"## Table of Contents",
		"",
	]
	content = []
	for section in sections:
		heading = f"{section['number']}. {section['title']}"
		lines.append(f"{section['number']}. [{section['title']}](#{anchor(heading)})")
		content.extend(
			[
				f"## {heading}",
				"",
				f"**Impact: {section['impact']}**",
				"",
				section["description"],
				"",
			]
		)
		selected = sorted(
			(rule for rule in rules if rule[0].stem.startswith(section["prefix"] + "-")),
			key=lambda rule: (rule[1]["title"].casefold(), rule[0].name),
		)
		for index, (path, fields, body) in enumerate(selected, start=1):
			heading = f"{section['number']}.{index} {fields['title']}"
			lines.append(f"   - [{heading}](#{anchor(heading)})")
			impact = fields["impact"]
			if fields.get("impactDescription"):
				impact += f" ({fields['impactDescription']})"
			content.extend(
				[
					f"### {heading}",
					"",
					f"Source: [{path.name}](../rules/{directory.name}/{path.name})",
					"",
					f"**Impact: {impact}**",
					"",
					body,
					"",
				]
			)
	return "\n".join([*lines, "", "---", "", *content]).rstrip() + "\n"


def main() -> int:
	parser = argparse.ArgumentParser(description="Compile local Vercel-derived rule references.")
	parser.add_argument("--check", action="store_true", help="Report drift without writing files.")
	args = parser.parse_args()
	outputs = []
	protocol = (ROOT / "skills/verify-review-findings/references/review-protocol.md").read_text(
		encoding="utf-8"
	)
	for name in SHARED_REVIEW_CONSUMERS:
		outputs.append(
			(
				ROOT / "skills" / name / "references/review-protocol.md",
				"<!-- Generated from verify-review-findings/references/review-protocol.md; edit that source. -->\n"
				+ protocol,
			)
		)
	for name, title in COLLECTIONS.items():
		package = ROOT / "skills/react-best-practices"
		directory = package / "rules" / name
		outputs.append(
			(package / "references" / f"{name}-rules.md", compile_collection(directory, title))
		)
	drift = False
	for path, content in outputs:
		if path.exists() and path.read_text(encoding="utf-8") == content:
			print(f"current: {path.relative_to(ROOT)}")
			continue
		drift = True
		if args.check:
			print(f"outdated: {path.relative_to(ROOT)}")
		else:
			path.parent.mkdir(parents=True, exist_ok=True)
			path.write_text(content, encoding="utf-8")
			print(f"generated: {path.relative_to(ROOT)}")
	return 1 if args.check and drift else 0


if __name__ == "__main__":
	raise SystemExit(main())
